language: node_js

stages:
  - deploy

branches:
  only:
    - master
    - develop

env:
  global:
    - AWS_REGION=us-east-1
    - FOLDR_META_BUCKET=foldr-us-east-1-prod
  
script:
  npm run test:cover && npx codecov

jobs:
  include:
    - stage: deploy
      script: npm run deploy
