language: node_js

stages:
  - test
  - deploy

branches:
  only:
    - master
    - develop

env:
  global:
    - AWS_REGION=us-east-1
    - FOLDR_META_BUCKET=foldr-us-east-1-prod

script: "true"

jobs:
  include:
    - stage: test
      script: npm run test:cover && npx codecov
    - stage: deploy
      script: npm run deploy
